easy_admin:
    design:
        assets:
            css:
                - 'assets/bs-tags/bootstrap-tagsinput.css'
                - 'css/app.css'
                - '/assets/smart-wizard/css/smart_wizard.css'
                - '/assets/smart-wizard/css/smart_wizard_theme_arrows.css'

            js:
                - 'assets/bs-tags/bootstrap-tagsinput.js'
                - '/assets/smart-wizard/js/jquery.smartWizard.js'
        menu:
            - { label: "Entities" }
            - label: "Posts"
              children:
                  - {entity: Post, label: "Post list", icon: "th-list"}
                  - {entity: Post, label: "Add post", icon: "plus", params: {action: 'new'}, permission: 'ROLE_ADMIN'}
            - label: "Categories"
              children:
                  - {entity: Category, label: "Category list", icon: "th-list"}
                  - {entity: Category, label: "Add category", icon: "plus", params: {action: 'new'}}
            - Tag
            - label: "Settings"
            - {entity: Users, icon: "user", permission: 'ROLE_ADMIN'}
            - Checkout
            - UsersActivities

    site_name: "Easy Admin Test"
    user:
        name_property_path: 'email'
    entities:
        # List the entity class name you want to manage
        Post:
            class: App\Entity\Post
            controller: App\Controller\PostController
            label: 'Post'
            list:
                collapse_actions: true
                actions: ['show', 'edit', 'delete']
                batch_actions: ['delete']
                title: "Some post"
                filters: ['published']
                fields:
                    - title
                    - content
                    - createdAt
                    - {property: 'thumbnail', type: "image", base_path: "%post_upload_path%"}
                    - {property: 'user.email', label: "Author", permission: 'ROLE_ADMIN'}

            show:
                fields:
                    - title
                    - {property: 'content', type: 'raw'}
                    - createdAt
                    - published
                    - {property: 'thumbnail', type: "image", base_path: "%post_upload_path%"}
                    - {property: 'attachments', template: "images.html.twig"}
                    - tags
            form:
                fields:
                    - {type: 'group', icon: 'pencil', label: 'Basic information', css_class: 'col-lg-7'}
                    - title
                    - {property: 'content', type: 'text_editor'}
                    - {type: 'group', icon: 'th-list', label: 'Other information', css_class: 'col-lg-5'}
                    - category
                    - {property: 'tags', type: 'App\Form\TagType', type_options: {attr: {data-role: 'tagsinput'}}, css_class: 'label label-danger'}
                    - createdAt
                    - published
                    - {type: 'group', icon: 'clip', label: 'Attachments', css_class: 'col-lg-12'}
                    - {property: 'thumbnailFile', type: 'vich_image'}
                    - {property: 'attachments', type: 'collection', type_options: {entry_type: 'App\Form\AttachmentType', by_reference: false}}

            edit:
                item_permission: 'ROLE_ADMIN'
                help: "Edition"
                #fields:
                 #   - '-tags'
            new:
                item_permission: 'ROLE_ADMIN'


        Category:
            class: App\Entity\Category

        UsersActivities:
            class: App\Entity\UsersActivities

        Tag:
            class: App\Entity\Tag
            form:
                fields:
                    - name
                    - slug
        Users:
            class: App\Entity\Users
            list:
                item_permission: 'ROLE_ADMIN'
        Checkout:
            class: App\Entity\Checkout
            templates:
                new: 'admin/checkout/new.html.twig'
            new:
                actions:
                    - '-list'
